// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUQo7E95tr9fXQwPNud0jKe8K4yOEqTtw',
    appId: '1:496351683809:web:fca3536132715a90ee83a0',
    messagingSenderId: '496351683809',
    projectId: 'save-wallet-app',
    authDomain: 'save-wallet-app.firebaseapp.com',
    storageBucket: 'save-wallet-app.firebasestorage.app',
    measurementId: 'G-LGDE7HL60H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB02ItHWK5xjSVTzgkD6oenstsE5Hs2JSI',
    appId: '1:496351683809:android:1cd9fe10fed8d564ee83a0',
    messagingSenderId: '496351683809',
    projectId: 'save-wallet-app',
    storageBucket: 'save-wallet-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN3VZ4nOUrEriCvvcjKn-v9rH_3sV_SJQ',
    appId: '1:496351683809:ios:aaf3ab0c53fd0a75ee83a0',
    messagingSenderId: '496351683809',
    projectId: 'save-wallet-app',
    storageBucket: 'save-wallet-app.firebasestorage.app',
    iosBundleId: 'com.example.cryptoCoinsList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN3VZ4nOUrEriCvvcjKn-v9rH_3sV_SJQ',
    appId: '1:496351683809:ios:aaf3ab0c53fd0a75ee83a0',
    messagingSenderId: '496351683809',
    projectId: 'save-wallet-app',
    storageBucket: 'save-wallet-app.firebasestorage.app',
    iosBundleId: 'com.example.cryptoCoinsList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUQo7E95tr9fXQwPNud0jKe8K4yOEqTtw',
    appId: '1:496351683809:web:a8f30f30927b1690ee83a0',
    messagingSenderId: '496351683809',
    projectId: 'save-wallet-app',
    authDomain: 'save-wallet-app.firebaseapp.com',
    storageBucket: 'save-wallet-app.firebasestorage.app',
    measurementId: 'G-136SR139GG',
  );
}
