// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:crypto_coins_list/repositories/crypto_coins/models/crypto_coin.dart';
import 'package:crypto_coins_list/repositories/crypto_coins/models/crypto_coins_details.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CryptoCoinAdapter());
    registerAdapter(CryptoCoinDetailAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CryptoCoinAdapter());
    registerAdapter(CryptoCoinDetailAdapter());
  }
}
